# -*- coding: utf-8 -*-
"""Magnitudes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jw-z6-N_xsEOYXNc4hEWCOxSBPwvBV2L

#Setup
"""

!pip install -q geopandas shapely folium xgboost scikit-learn pandas numpy matplotlib seaborn

# Data handling
import pandas as pd
import numpy as np

# Geospasial
import geopandas as gpd
from shapely.geometry import Point

# Visualize
import matplotlib.pyplot as plt
import seaborn as sns
import folium

# Machine learning
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, f1_score
import xgboost as xgb

# Google Colab
from google.colab import drive

# Utility
import warnings
warnings.filterwarnings('ignore')

# Mount & Load Google Drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/Indoearthquake/datagempa.csv")

# Data card
print("="*50)
print("DATA CARD: Katalog Gempa Indonesia")
print("="*50)

print(f"\nJumlah baris\t: {df.shape[0]:,}")
print(f"Jumlah kolom\t: {df.shape[1]}")

print(f"\nKolom & tipe data:")
print(df.dtypes)

print(f"\nMissing values per kolom:")
print(df.isna().sum())

print(f"\nRentang tanggal:")
print(f"  {df['tgl'].min()}  s/d  {df['tgl'].max()}")

print(f"\nStatistik deskriptif (fitur numerik):")
print(df[['lat','lon','depth','mag']].describe())

print(f"\nJumlah lokasi unik (remark)\t: {df['remark'].nunique()}")

print(f"\nDuplikat baris penuh\t: {df.duplicated().sum()}")

"""#Exploratory Data Analysis"""

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

sns.histplot(df['mag'], bins=50, kde=True, ax=axes[0,0], color='steelblue')
axes[0,0].set_title('Distribusi Magnitude')

sns.histplot(df['depth'], bins=50, kde=True, ax=axes[0,1], color='darkorange')
axes[0,1].set_title('Distribusi Depth (km)')

sns.histplot(df['lat'], bins=50, kde=True, ax=axes[1,0], color='seagreen')
axes[1,0].set_title('Distribusi Latitude')

sns.histplot(df['lon'], bins=50, kde=True, ax=axes[1,1], color='indianred')
axes[1,1].set_title('Distribusi Longitude')

plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.boxplot(x=df['mag'], ax=axes[0], color='steelblue')
axes[0].set_title('Boxplot Magnitude')

sns.boxplot(x=df['depth'], ax=axes[1], color='darkorange')
axes[1].set_title('Boxplot Depth')

plt.tight_layout()
plt.show()

Q1_mag = df['mag'].quantile(0.25)
Q3_mag = df['mag'].quantile(0.75)
IQR_mag = Q3_mag - Q1_mag
outlier_mag = df[(df['mag'] < Q1_mag - 1.5*IQR_mag) | (df['mag'] > Q3_mag + 1.5*IQR_mag)]
print("Jumlah outlier magnitude:", len(outlier_mag))

Q1_depth = df['depth'].quantile(0.25)
Q3_depth = df['depth'].quantile(0.75)
IQR_depth = Q3_depth - Q1_depth
outlier_depth = df[(df['depth'] < Q1_depth - 1.5*IQR_depth) | (df['depth'] > Q3_depth + 1.5*IQR_depth)]
print("Jumlah outlier depth:", len(outlier_depth))

df_time = df.copy()
df_time['tgl'] = pd.to_datetime(df_time['tgl'])
df_time['year'] = df_time['tgl'].dt.year
df_time['month'] = df_time['tgl'].dt.month

yearly_counts = df_time.groupby('year').size()
yearly_mag = df_time.groupby('year')['mag'].mean()

fig, axes = plt.subplots(2, 1, figsize=(14, 10))

yearly_counts.plot(kind='bar', ax=axes[0], color='steelblue')
axes[0].set_title('Jumlah Gempa per Tahun (2008-2023)')
axes[0].set_ylabel('Jumlah Event')

yearly_mag.plot(kind='line', marker='o', ax=axes[1], color='indianred')
axes[1].set_title('Rata-rata Magnitude per Tahun')
axes[1].set_ylabel('Magnitude')

plt.tight_layout()
plt.show()

monthly_counts = df_time.groupby('month').size()
plt.figure(figsize=(10,5))
sns.barplot(x=monthly_counts.index, y=monthly_counts.values, color='seagreen')
plt.title('Distribusi Jumlah Gempa per Bulan (Agregat Seluruh Tahun)')
plt.xlabel('Bulan')
plt.ylabel('Jumlah Event')
plt.show()

corr_cols = ['lat','lon','depth','mag']
corr_matrix = df[corr_cols].corr()

plt.figure(figsize=(8,6))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.3f', square=True)
plt.title('Korelasi Antar Fitur Numerik')
plt.show()

sns.pairplot(df[corr_cols], diag_kind='kde', plot_kws={'alpha':0.3, 's':10})
plt.suptitle('Pairplot Fitur Numerik', y=1.02)
plt.show()

# Depth vs Magnitude
fig, axes = plt.subplots(1, 2, figsize=(14,6))

axes[0].scatter(df['depth'], df['mag'], alpha=0.2, s=8, color='steelblue')
axes[0].set_xlabel('Depth (km)')
axes[0].set_ylabel('Magnitude')
axes[0].set_title('Scatter Depth vs Magnitude')

sns.kdeplot(x=df['depth'], y=df['mag'], cmap='viridis', fill=True, ax=axes[1])
axes[1].set_title('Density Plot Depth vs Magnitude')

plt.tight_layout()
plt.show()

bins_depth = [0,20,70,300,750]
labels_depth = ['Dangkal(0-20)','Menengah(20-70)','Dalam(70-300)','SangatDalam(300-750)']
depth_cat = pd.cut(df['depth'], bins=bins_depth, labels=labels_depth)
depth_mag_summary = df.groupby(depth_cat)['mag'].agg(['mean','std','count'])
print(depth_mag_summary)

plt.figure(figsize=(10,10))
scatter = plt.scatter(df['lon'], df['lat'], c=df['mag'], cmap='YlOrRd', alpha=0.4, s=8)
plt.colorbar(scatter, label='Magnitude')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.title('Sebaran Spasial Gempa di Indonesia (Warna = Magnitude)')
plt.scatter(105.423, -6.102, color='blue', marker='*', s=300, label='Anak Krakatau')
plt.legend()
plt.show()

top_remark = df['remark'].value_counts().head(20)

plt.figure(figsize=(10,8))
sns.barplot(x=top_remark.values, y=top_remark.index, palette='viridis')
plt.title('20 Wilayah dengan Jumlah Gempa Terbanyak')
plt.xlabel('Jumlah Event')
plt.show()

remark_mag_summary = df.groupby('remark')['mag'].agg(['mean','max','count']).sort_values('count', ascending=False).head(20)
print(remark_mag_summary)

lat0, lon0 = -6.102, 105.423

def haversine(lat1, lon1, lat2, lon2):
    R = 6371
    p1, p2 = np.radians(lat1), np.radians(lat2)
    dp = np.radians(lat2 - lat1)
    dl = np.radians(lon2 - lon1)
    a = np.sin(dp/2)**2 + np.cos(p1)*np.cos(p2)*np.sin(dl/2)**2
    return 2 * R * np.arcsin(np.sqrt(a))

df_dist = df.copy()
df_dist['dist_km'] = haversine(lat0, lon0, df_dist['lat'], df_dist['lon'])

for r in [20, 50, 100, 150, 300]:
    count = (df_dist['dist_km'] <= r).sum()
    print(f"Radius {r} km: {count} event")

df_krakatau = df_dist[df_dist['dist_km'] <= 150].copy()
df_krakatau['tgl'] = pd.to_datetime(df_krakatau['tgl'])
df_krakatau['year'] = df_krakatau['tgl'].dt.year

yearly_krakatau = df_krakatau.groupby('year').size()

plt.figure(figsize=(12,5))
sns.barplot(x=yearly_krakatau.index, y=yearly_krakatau.values, color='crimson')
plt.title('Aktivitas Gempa dalam Radius 150km dari Anak Krakatau per Tahun')
plt.xlabel('Tahun')
plt.ylabel('Jumlah Event')
plt.xticks(rotation=45)
plt.show()

df_fm = df.dropna(subset=['strike1','dip1','rake1']).copy()
print("Jumlah baris dengan focal mechanism:", len(df_fm))

fig, axes = plt.subplots(1, 3, figsize=(16,5))

sns.histplot(df_fm['strike1'], bins=30, ax=axes[0], color='steelblue')
axes[0].set_title('Distribusi Strike1')

sns.histplot(df_fm['dip1'], bins=30, ax=axes[1], color='darkorange')
axes[1].set_title('Distribusi Dip1')

sns.histplot(df_fm['rake1'], bins=30, ax=axes[2], color='seagreen')
axes[2].set_title('Distribusi Rake1')

plt.tight_layout()
plt.show()

plt.figure(figsize=(8,6))
sns.scatterplot(x=df_fm['mag'], y=df_fm['depth'], hue=df_fm['rake1'], palette='coolwarm', s=40)
plt.title('Depth vs Magnitude untuk Event dengan Focal Mechanism')
plt.gca().invert_yaxis()
plt.show()

"""#PreProcessing"""

df_pre = df.copy()
df_pre['datetime'] = pd.to_datetime(df_pre['tgl'] + ' ' + df_pre['ot'])

df_pre = df_pre.drop(columns=['strike1','dip1','rake1','strike2','dip2','rake2','tgl','ot'])

lat0, lon0 = -6.102, 105.423

def haversine(lat1, lon1, lat2, lon2):
    R = 6371
    p1, p2 = np.radians(lat1), np.radians(lat2)
    dp = np.radians(lat2 - lat1)
    dl = np.radians(lon2 - lon1)
    a = np.sin(dp/2)**2 + np.cos(p1)*np.cos(p2)*np.sin(dl/2)**2
    return 2 * R * np.arcsin(np.sqrt(a))

df_pre['dist_km'] = haversine(lat0, lon0, df_pre['lat'], df_pre['lon'])

bins = [0, 4, 6, 9]
labels = ['kecil', 'sedang', 'besar']
df_pre['mag_class'] = pd.cut(df_pre['mag'], bins=bins, labels=labels)

df_pre['month'] = df_pre['datetime'].dt.month
df_pre['dayofweek'] = df_pre['datetime'].dt.dayofweek

print(df_pre.columns.tolist())

le_remark = LabelEncoder()
df_pre['remark_encoded'] = le_remark.fit_transform(df_pre['remark'])

features = ['lat', 'lon', 'depth', 'dist_km', 'month', 'dayofweek', 'remark_encoded']
X = df_pre[features]
y = df_pre['mag_class']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

le_target = LabelEncoder()
y_train_enc = le_target.fit_transform(y_train)
y_test_enc = le_target.transform(y_test)

class_counts = pd.Series(y_train_enc).value_counts().sort_index()
total = len(y_train_enc)
sample_weights = pd.Series(y_train_enc).map(lambda c: total / (len(class_counts) * class_counts[c])).values

print(df_pre.shape)
print(df_pre[['datetime','dist_km','mag_class','remark_encoded','month','dayofweek']].head())
print(y_train.value_counts())
print(y_test.value_counts())
print(X_train.shape, X_test.shape)

"""#XGBoost"""

xgb_model = xgb.XGBClassifier(
    objective='multi:softprob',
    num_class=3,
    n_estimators=500,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=3,
    gamma=0.1,
    reg_alpha=0.1,
    reg_lambda=1.0,
    eval_metric='mlogloss',
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(
    X_train, y_train_enc,
    sample_weight=sample_weights,
    eval_set=[(X_train, y_train_enc), (X_test, y_test_enc)],
    verbose=50
)

results = xgb_model.evals_result()

plt.figure(figsize=(10,6))
plt.plot(results['validation_0']['mlogloss'], label='Train')
plt.plot(results['validation_1']['mlogloss'], label='Test')
plt.xlabel('Iterasi')
plt.ylabel('Multi-class Log Loss')
plt.title('Kurva Pembelajaran XGBoost')
plt.legend()
plt.show()

y_pred_enc = xgb_model.predict(X_test)
y_pred = le_target.inverse_transform(y_pred_enc)
y_pred_proba = xgb_model.predict_proba(X_test)

print(classification_report(y_test, y_pred, target_names=le_target.classes_, digits=4))

f1_macro = f1_score(y_test, y_pred, average='macro')
f1_weighted = f1_score(y_test, y_pred, average='weighted')
print("F1 Macro:", f1_macro)
print("F1 Weighted:", f1_weighted)

"""besar	0.184	0.587	0.280	Model menangkap 58.7% gempa besar yang sebenarnya (recall lumayan!), tapi dari semua yang diprediksi "besar", cuma 18.4% yang benar, banyak false alarm

kecil	0.851	0.806	0.828	Bagus, model cukup andal untuk kelas mayoritas ini

sedang	0.578	0.638	0.606	Cukup lumayan, tapi masih banyak salah klasifikasi
"""

cm = confusion_matrix(y_test, y_pred, labels=le_target.classes_)
cm_norm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

fig, axes = plt.subplots(1, 2, figsize=(16,6))

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=le_target.classes_, yticklabels=le_target.classes_, ax=axes[0])
axes[0].set_title('Confusion Matrix (Absolute)')
axes[0].set_xlabel('Predicted')
axes[0].set_ylabel('Actual')

sns.heatmap(cm_norm, annot=True, fmt='.2%', cmap='Greens', xticklabels=le_target.classes_, yticklabels=le_target.classes_, ax=axes[1])
axes[1].set_title('Confusion Matrix (Normalized)')
axes[1].set_xlabel('Predicted')
axes[1].set_ylabel('Actual')

plt.tight_layout()
plt.show()

importance_gain = xgb_model.get_booster().get_score(importance_type='gain')
importance_weight = xgb_model.get_booster().get_score(importance_type='weight')

df_importance = pd.DataFrame({
    'feature': list(importance_gain.keys()),
    'gain': list(importance_gain.values())
}).sort_values('gain', ascending=False)

plt.figure(figsize=(10,6))
sns.barplot(data=df_importance, x='gain', y='feature', palette='viridis')
plt.title('Feature Importance (Gain)')
plt.show()

print(df_importance)

from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.preprocessing import label_binarize

y_test_bin = label_binarize(y_test_enc, classes=[0,1,2])

plt.figure(figsize=(8,8))
for i, cls_name in enumerate(le_target.classes_):
    fpr, tpr, _ = roc_curve(y_test_bin[:, i], y_pred_proba[:, i])
    auc = roc_auc_score(y_test_bin[:, i], y_pred_proba[:, i])
    plt.plot(fpr, tpr, label=f'{cls_name} (AUC={auc:.3f})')

plt.plot([0,1],[0,1], linestyle='--', color='gray')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve per Kelas')
plt.legend()
plt.show()

xgb_model.save_model('/content/drive/MyDrive/Indoearthquake/xgb_magnitude_model.json')

import joblib
joblib.dump(le_target, '/content/drive/MyDrive/Indoearthquake/le_target.pkl')
joblib.dump(le_remark, '/content/drive/MyDrive/Indoearthquake/le_remark.pkl')

X_full = df_pre[features]
y_full_pred_enc = xgb_model.predict(X_full)
df_pre['predicted_class'] = le_target.inverse_transform(y_full_pred_enc)

gdf = gpd.GeoDataFrame(
    df_pre,
    geometry=gpd.points_from_xy(df_pre['lon'], df_pre['lat']),
    crs='EPSG:4326'
)

fig, axes = plt.subplots(1, 2, figsize=(18,9))

color_map = {'kecil':'green', 'sedang':'orange', 'besar':'red'}

for cls, color in color_map.items():
    subset = gdf[gdf['mag_class'] == cls]
    subset.plot(ax=axes[0], color=color, markersize=3, alpha=0.5, label=cls)

axes[0].scatter(105.423, -6.102, color='blue', marker='*', s=300, label='Anak Krakatau')
axes[0].set_title('Aktual (mag_class)')
axes[0].legend()

for cls, color in color_map.items():
    subset = gdf[gdf['predicted_class'] == cls]
    subset.plot(ax=axes[1], color=color, markersize=3, alpha=0.5, label=cls)

axes[1].scatter(105.423, -6.102, color='blue', marker='*', s=300, label='Anak Krakatau')
axes[1].set_title('Prediksi (predicted_class)')
axes[1].legend()

plt.tight_layout()
plt.show()

"""# Interactive Map"""

import folium
import json
from folium.plugins import HeatMap, MiniMap, MeasureControl
from branca.colormap import LinearColormap
from shapely.geometry import mapping

gdf_map = gdf[gdf['dist_km'] <= 150].copy()

m = folium.Map(location=[-6.102, 105.423], zoom_start=9, tiles='CartoDB positron')

color_map = {'kecil':'green', 'sedang':'orange', 'besar':'red'}

for _, row in gdf_map.iterrows():
    folium.CircleMarker(
        location=[row['lat'], row['lon']],
        radius=4 if row['predicted_class']=='kecil' else (6 if row['predicted_class']=='sedang' else 9),
        color=color_map[row['predicted_class']],
        fill=True,
        fill_color=color_map[row['predicted_class']],
        fill_opacity=0.6,
        popup=folium.Popup(
            f"Datetime: {row['datetime']}<br>"
            f"Mag: {row['mag']}<br>"
            f"Depth: {row['depth']} km<br>"
            f"Aktual: {row['mag_class']}<br>"
            f"Prediksi: {row['predicted_class']}<br>"
            f"Jarak Krakatau: {row['dist_km']:.1f} km",
            max_width=250
        )
    ).add_to(m)

folium.Marker(
    location=[-6.102, 105.423],
    popup='Anak Krakatau',
    icon=folium.Icon(color='blue', icon='star', prefix='fa')
).add_to(m)

MiniMap(toggle_display=True).add_to(m)
MeasureControl(primary_length_unit='kilometers').add_to(m)

legend_html = '''
<div style="position: fixed; bottom: 30px; left: 30px; width: 140px; z-index:9999;
            background-color:white; padding:10px; border:2px solid grey; border-radius:5px;
            font-size:14px;">
<b>Prediksi Kelas</b><br>
<i style="background:green; width:10px; height:10px; display:inline-block; border-radius:50%;"></i> Kecil<br>
<i style="background:orange; width:10px; height:10px; display:inline-block; border-radius:50%;"></i> Sedang<br>
<i style="background:red; width:10px; height:10px; display:inline-block; border-radius:50%;"></i> Besar<br>
</div>
'''
m.get_root().html.add_child(folium.Element(legend_html))

m

m_heat = folium.Map(location=[-6.102, 105.423], zoom_start=9, tiles='CartoDB dark_matter')

heat_data = gdf_map[['lat','lon','mag']].values.tolist()

HeatMap(heat_data, radius=15, blur=20, max_zoom=10).add_to(m_heat)

folium.Marker(
    location=[-6.102, 105.423],
    popup='Anak Krakatau',
    icon=folium.Icon(color='red', icon='star', prefix='fa')
).add_to(m_heat)

m_heat